CREATE DATABASE powerpoints;
\c powerpoints;


CREATE TABLE IF NOT EXISTS teams (
  id SERIAL not null, 
  school text NOT NULL,
  mascot text NOT NULL,
  class int NOT NULL,
  tracked char(1) NOT NULL,
  district text,
  confID int,
  points decimal(4,2) NOT NULL default 0.00,
  pmax decimal(4,2) NOT NULL default 0.00,
  pmin decimal(4,2) NOT NULL default 0.00,
  week1 int,
  week2 int,
  week3 int,
  week4 int,
  week5 int,
  week6 int,
  week7 int,
  week8 int,
  week9 int,
  week10 int,
  week11 int,
  week12 int,
  PRIMARY KEY(id)
);


insert into teams (school, mascot, class, tracked, district, confID) values ('Albemarle', 'Patriot', 5, 'Y', 'Jefferson', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Annandale', 'Atoms', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('Atlee', 'Raiders', 5, 'Y', 'Capital', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Battlefield', 'Bobcats', 6, 'Y', 'Cardinal', 8);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bayside', 'Marlins', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bethel', 'Bruins', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Briar Woods', 'Falcons', 5, 'Y', 'Potomac', 14);
insert into teams (school, mascot, class, tracked, district, confID) values ('Broad Run', 'Spartans', 5, 'Y', 'Potomac', 14);
insert into teams (school, mascot, class, tracked, district, confID) values ('Brooke Point', 'Black-Hawks', 5, 'Y', 'Commonwealth', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Caroline', 'Cavaliers', 4, 'Y', 'Battlefield', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Centreville', 'Wildcats', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Chancellor', 'Chargers', 4, 'Y', 'Battlefield', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Chantilly', 'Chargers', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Churchland', 'Truckers', 4, 'Y', 'Eastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('Colonial Forge', 'Eagles', 6, 'Y', 'Commonwealth', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Cosby', 'Titans', 6, 'Y', 'Dominion', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('Courtland', 'Cougars', 4, 'Y', 'Battlefield', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Cox', 'Falcons', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Clover Hill', 'Cavaliers', 6, 'Y', 'Dominion', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('Deep Creek', 'Hornets', 4, 'Y', 'Southeastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('Deep Run', 'Wildcats', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Denbigh', 'Patriots', 4, 'Y', 'Peninsula', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('Dinwiddie', 'Generals', 4, 'Y', 'Central', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Douglas Freeman', 'Rebels', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Eastern View', 'Cyclones', 4, 'Y', 'Evergreen', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Fairfax', 'Rebel Pride', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('Falls Church', 'Jaguars', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('First Colonial', 'Patriots', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Forest Park', 'Bruins', 6, 'Y', 'Cardinal', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Franklin Co.', 'Eagles', 6, 'Y', 'Piedmont', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('Freedom (PW)', 'Eagles', 6, 'Y', 'Cardinal', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Gar-Field', 'Indians', 6, 'Y', 'Cardinal', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('George Marshall', 'Statesmen', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Glen Allen', 'Jaguars', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Gloucester', 'Dukes', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Grafton', 'Clippers', 4, 'Y', 'Bay Rivers', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('Granby', 'Comets', 6, 'Y', 'Eastern', 2);
insert into teams (school, mascot, class, tracked, district, confID) values ('Grassfield', 'Grizzlies', 6, 'Y', 'Southeastern', 2);
insert into teams (school, mascot, class, tracked, district, confID) values ('Great Bridge', 'Wildcats', 4, 'Y', 'Southeastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('Green Run', 'Stallions', 5, 'Y', 'Beach', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('Halifax Co.', 'Comets', 5, 'Y', 'Piedmont', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hampton', 'Crabbers', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hanover', 'Hawks', 4, 'Y', 'Capital', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hayfield', 'Hawks', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('Henrico', 'Warriors', 5, 'Y', 'Capital', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Heritage (NN)', 'Hurricanes', 4, 'Y', 'Peninsula', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hermitage', 'Panthers', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Herndon', 'Fighting Hornets', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hickory', 'Hawks', 5, 'Y', 'Southeastern', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('Highland Springs', 'Springers', 5, 'Y', 'Capital', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('Huguenot', 'Falcons', 4, 'Y', 'Dominion', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hylton', 'Bulldogs', 6, 'Y', 'Cardinal', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Indian River', 'Fighting Braves', 5, 'Y', 'Southeastern', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('J.R. Tucker', 'Tigers', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('James Madison', 'Warhawks', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('James River (Ch)', 'Rapids', 6, 'Y', 'Dominion', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('James Robinson', 'Rams', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Jamestown', 'Eagles', 4, 'Y', 'Bay Rivers', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('JEB Stuart', 'Raiders', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Kecoughtan', 'Warriors', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Kellam', 'Knights', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Kempsville', 'Chiefs', 5, 'Y', 'Beach', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('King George', 'Foxes', 4, 'Y', 'Battlefield', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Kings Fork', 'Bulldogs', 4, 'Y', 'Southeastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('L.C. Bird', 'Skyhawks', 5, 'Y', 'Dominion', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lake Taylor', 'Titans', 4, 'Y', 'Eastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lafayette', 'Rams', 4, 'Y', 'Bay Rivers', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lake Braddock', 'Bruins', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('Landstown', 'Eagles', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Langley', 'Saxons', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lee-Davis', 'Confederates', 5, 'Y', 'Capital', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Louisa', 'Lions', 4, 'Y', 'Jefferson', 19);
insert into teams (school, mascot, class, tracked, district, confID) values ('Manchester', 'Lancers', 6, 'Y', 'Dominion', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('Massaponax', 'Panthers', 5, 'Y', 'Commonwealth', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Matoaca', 'Warriors', 5, 'Y', 'Central', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('Maury', 'Commodores', 5, 'Y', 'Eastern', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('McLean', 'Highlanders', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('Meadowbrook', 'Monarchs', 5, 'Y', 'Central', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('Menchville', 'Monarchs', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Midlothian', 'Trojans', 4, 'Y', 'Dominion', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Mills Godwin', 'Eagles', 5, 'Y', 'Colonial', 11);
insert into teams (school, mascot, class, tracked, district, confID) values ('Monacan', 'Chiefs', 4, 'Y', 'Dominion', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Mount Vernon', 'Majors', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('Mountain View', 'Wildcats', 5, 'Y', 'Commonwealth', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Nansemond River', 'Warriors', 5, 'Y', 'Southeastern', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('North Stafford', 'Wolverines', 5, 'Y', 'Commonwealth', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Norview', 'Pilots', 5, 'Y', 'Eastern', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('Oakton', 'Cougars', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Ocean Lakes', 'Dolphins', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('Orange', 'Hornets', 5, 'Y', 'Jefferson', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Osbourn', 'Eagles', 6, 'Y', 'Cardinal', 8);
insert into teams (school, mascot, class, tracked, district, confID) values ('Osbourn Park', 'Yellow Jackets', 6, 'Y', 'Cardinal', 8);
insert into teams (school, mascot, class, tracked, district, confID) values ('Oscar Smith', 'Tigers', 6, 'Y', 'Southeastern', 2);
insert into teams (school, mascot, class, tracked, district, confID) values ('Patrick Henry (Ash)', 'Patriots', 5, 'Y', 'Capitals', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Patrick Henry (Roa)', 'Patriots', 5, 'Y', 'River Ridge', 16);
insert into teams (school, mascot, class, tracked, district, confID) values ('Patriot', 'Pioneers', 6, 'Y', 'Cardinal', 8);
insert into teams (school, mascot, class, tracked, district, confID) values ('Potomac', 'Panthers', 5, 'Y', 'Cardinal', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Potomac Falls', 'Panthers', 5, 'Y', 'Potomac', 14);
insert into teams (school, mascot, class, tracked, district, confID) values ('Powhatan', 'Indians', 4, 'Y', 'Jefferson', 20);
insert into teams (school, mascot, class, tracked, district, confID) values ('Prince George', 'Royals', 5, 'Y', 'Central', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('Princess Anne', 'Cavaliers', 5, 'Y', 'Beach', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('R.E. Lee (Spr)', 'Lancers', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Riverbend', 'Bears', 6, 'Y', 'Commonwealth', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Salem (VB)', 'SunDevils', 5, 'Y', 'Beach', 9);
insert into teams (school, mascot, class, tracked, district, confID) values ('Smithfield', 'Packers', 4, 'Y', 'Bay Rivers', 18);
insert into teams (school, mascot, class, tracked, district, confID) values ('South County', 'Stallions', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('South Lakes', 'Seahawks', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('Stafford', 'Indians', 5, 'Y', 'Commonwealth', 15);
insert into teams (school, mascot, class, tracked, district, confID) values ('Stone Bridge', 'Bulldogs', 5, 'Y', 'Potomac', 14);
insert into teams (school, mascot, class, tracked, district, confID) values ('Stonewall Jackson', 'Raiders', 6, 'Y', 'Cardinal', 8);
insert into teams (school, mascot, class, tracked, district, confID) values ('Tallwood', 'Lions', 6, 'Y', 'Beach', 1);
insert into teams (school, mascot, class, tracked, district, confID) values ('T.C. Williams', 'Titans', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('T. Jefferson (Ale)', 'Colonials', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Thomas Dale', 'Knights', 6, 'Y', 'Central', 3);
insert into teams (school, mascot, class, tracked, district, confID) values ('Thomas Edison', 'Eagles', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Tuscarora', 'Huskies', 5, 'Y', 'Potomac', 14);
insert into teams (school, mascot, class, tracked, district, confID) values ('Varina', 'Blue Devils', 5, 'Y', 'Capital', 12);
insert into teams (school, mascot, class, tracked, district, confID) values ('W.T. Woodson', 'Cavaliers', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('Wakefield', 'Warriors', 5, 'Y', 'District 13', 13);
insert into teams (school, mascot, class, tracked, district, confID) values ('Warwick', 'Raiders', 5, 'Y', 'Peninsula', 10);
insert into teams (school, mascot, class, tracked, district, confID) values ('Washington-Lee', 'Generals', 6, 'Y', 'District 6', 6);
insert into teams (school, mascot, class, tracked, district, confID) values ('West Potomac', 'Wolverines', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('West Springfield', 'Spartans', 6, 'Y', 'District 7', 7);
insert into teams (school, mascot, class, tracked, district, confID) values ('Western Branch', 'Bruins', 6, 'Y', 'Southeastern', 2);
insert into teams (school, mascot, class, tracked, district, confID) values ('Westfield', 'Bulldogs', 6, 'Y', 'District 5', 5);
insert into teams (school, mascot, class, tracked, district, confID) values ('Woodbridge', 'Vikings', 6, 'Y', 'Cardinal', 4);
insert into teams (school, mascot, class, tracked, district, confID) values ('Woodrow Wilson', 'Presidents', 4, 'Y', 'Eastern', 17);
insert into teams (school, mascot, class, tracked, district, confID) values ('Woodside', 'Wolverines', 6, 'Y', 'Peninsula', 2);
insert into teams (school, mascot, class, tracked, district, confID) values ('Yorktown', 'Patriots', 6, 'Y', 'District 6', 6);



insert into teams (school, mascot, class, tracked, district, confID) values ('William Byrd', 'Terriers', 4, 'Y', 'Blue Ridge', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('William Fleming', 'Colonels', 4, 'Y', 'Blue Ridge', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('John Champe', 'Knights', 4, 'Y', 'Dulles', 22);
insert into teams (school, mascot, class, tracked, district, confID) values ('Dominion', 'Titans', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Freedom (LC)', 'Eagles', 4, 'Y', 'Dulles', 22);
insert into teams (school, mascot, class, tracked, district, confID) values ('Heritage (LC)', 'Pride', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Loudoun Co.', 'Raiders', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Loudoun Valley', 'Vikings', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Park View (St)', 'Patriots', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rock Ridge', 'Phoenix', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Woodgrove', 'Wolverines', 4, 'Y', 'Dulles', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Fauquier', 'Falcons', 4, 'Y', 'Evergreen', 22);
insert into teams (school, mascot, class, tracked, district, confID) values ('Kettle Run', 'Cougars', 4, 'Y', 'Evergreen', 22);
insert into teams (school, mascot, class, tracked, district, confID) values ('Liberty (Beal)', 'Eagles', 4, 'Y', 'Evergreen', 22);
insert into teams (school, mascot, class, tracked, district, confID) values ('Charlottesville', 'Black Knights', 4, 'Y', 'Jefferson', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('Handley', 'Judges', 4, 'Y', 'Northwestern', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Millbrook', 'Pioneers', 4, 'Y', 'Northwestern', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Sherando', 'Warriors', 4, 'Y', 'Northwestern', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('James Wood', 'Colonels', 4, 'Y', 'Northwestern', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bassett', 'Bengals', 4, 'Y', 'Piedmont', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('George Washington', 'Eagles', 4, 'Y', 'Piedmont', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('Pulaski Co.', 'Cougars', 4, 'Y', 'River Ridge', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('Salem (Sa)', 'Spartans', 4, 'Y', 'River Ridge', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('Carroll Co.', 'Cavaliers', 4, 'Y', 'River Ridge', 24);
insert into teams (school, mascot, class, tracked, district, confID) values ('Amherst Co.', 'Lancers', 4, 'Y', 'Seminole', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('E.C. Glass', 'Hilltoppers', 4, 'Y', 'Seminole', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('Jefferson Forest', 'Cavaliers', 4, 'Y', 'Seminole', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('Liberty Christian', 'Bulldogs', 4, 'Y', 'Seminole', 23);
insert into teams (school, mascot, class, tracked, district, confID) values ('Harrisonburg', 'Blue Streaks', 4, 'Y', 'Valley', 21);
insert into teams (school, mascot, class, tracked, district, confID) values ('James Monroe', 'Yellow Jackets', 3, 'Y', 'Battlefield', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Spotsylvania', 'Knights', 3, 'Y', 'Battlefield', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('New Kent', 'Trojans', 3, 'Y', 'Bay Rivers', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('Poquoson', 'Islanders', 3, 'Y', 'Bay Rivers', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('Tabb', 'Tigers', 3, 'Y', 'Bay Rivers', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('Warhill', 'Lions', 3, 'Y', 'Bay Rivers', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('York', 'Falcons', 3, 'Y', 'Bay Rivers', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('William Monroe', 'Dragons', 3, 'Y', 'Bull Run', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Warren Co.', 'Wildcats', 3, 'Y', 'Bull Run', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Armstrong', 'Wildcats', 3, 'Y', 'Capital', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('Colonial Heights', 'Colonials', 3, 'Y', 'Central', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hopewell', 'Blue Devils', 3, 'Y', 'Central', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('Petersburg', 'Crimson Wave', 3, 'Y', 'Central', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('T. Jefferson (Ri)', 'Vikings', 3, 'Y', 'Colonial', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('John Marshall', 'Justices', 3, 'Y', 'Colonial', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('George Wythe (Ri)', 'Bulldogs', 3, 'Y', 'Dominion', 26);
insert into teams (school, mascot, class, tracked, district, confID) values ('Riverside', 'Rams', 3, 'Y', 'Dulles', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('I.C. Norcom', 'Greyhounds', 3, 'Y', 'Eastern', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('B.T. Washington', 'Mighty Bookers', 3, 'Y', 'Eastern', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('Brentsville', 'Tigers', 3, 'Y', 'Evergreen', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Culpeper', 'Blue Devils', 3, 'Y', 'Evergreen', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Manassas Park', 'Cougars', 3, 'Y', 'Evergreen', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Skyline', 'Hawks', 3, 'Y', 'Northwestern', 28);
insert into teams (school, mascot, class, tracked, district, confID) values ('Phoebus', 'Phantoms', 3, 'Y', 'Peninsula', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lakeland', 'Cavaliers', 3, 'Y', 'Southeastern', 27);
insert into teams (school, mascot, class, tracked, district, confID) values ('Park View (SH)', 'Dragons', 3, 'Y', 'Tri-Rivers', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('Southampton', 'xx', 3, 'Y', 'Tri-Rivers', 25);
insert into teams (school, mascot, class, tracked, district, confID) values ('Alleghany', 'Mountaineers', 3, 'Y', 'Blue Ridge', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lord Botetourt', 'Cavaliers', 3, 'Y', 'Blue Ridge', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Northside', 'Vikings', 3, 'Y', 'Blue Ridge', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rockbridge Co.', 'Wildcats', 3, 'Y', 'Blue Ridge', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Staunton River', 'Golden Eagles', 3, 'Y', 'Blue Ridge', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Fluvanna', 'Flucos', 3, 'Y', 'Jefferson', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Monticello', 'Mustangs', 3, 'Y', 'Jefferson', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Western Albemarle', 'Warriors', 3, 'Y', 'Jefferson', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Patrick Co.', 'Cougars', 3, 'Y', 'Piedmont', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Tunstall', 'Trojans', 3, 'Y', 'Piedmont', 30);
insert into teams (school, mascot, class, tracked, district, confID) values ('Magna Vista', 'Warriors', 3, 'Y', 'Piedmont', 31);
insert into teams (school, mascot, class, tracked, district, confID) values ('Blacksburg', 'Bruins', 3, 'Y', 'River Ridge', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Cave Spring', 'Knights', 3, 'Y', 'River Ridge', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Christiansburg', 'Demons', 3, 'Y', 'River Ridge', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hidden Valley', 'Titans', 3, 'Y', 'River Ridge', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Brookville', 'Bees', 3, 'Y', 'Seminole', 30);
insert into teams (school, mascot, class, tracked, district, confID) values ('Heritage (Ly)', 'Pioneers', 3, 'Y', 'Seminole', 30);
insert into teams (school, mascot, class, tracked, district, confID) values ('Liberty (Bed)', 'Minutemen', 3, 'Y', 'Seminole', 30);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rustburg', 'Devils', 3, 'Y', 'Seminole', 30);
insert into teams (school, mascot, class, tracked, district, confID) values ('Abingdon', 'Falcons', 3, 'Y', 'Southwest', 32);
insert into teams (school, mascot, class, tracked, district, confID) values ('Broadway', 'Gobblers', 3, 'Y', 'Valley', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Fort Defiance', 'Indians', 3, 'Y', 'Valley', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Spotswood', 'Trailblazers', 3, 'Y', 'Valley', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Turner Ashby', 'Knights', 3, 'Y', 'Valley', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Waynesboro', 'Little Giants', 3, 'Y', 'Valley', 29);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bruton', 'Panthers', 2, 'Y', 'Bay Rivers', 33);
insert into teams (school, mascot, class, tracked, district, confID) values ('Central (Wo)', 'Falcons', 2, 'Y', 'Bull Run', 35);
insert into teams (school, mascot, class, tracked, district, confID) values ('Clarke Co.', 'Eagles', 2, 'Y', 'Bull Run', 35);
insert into teams (school, mascot, class, tracked, district, confID) values ('Madison Co.', 'Mountaineers', 2, 'Y', 'Bull Run', 35);
insert into teams (school, mascot, class, tracked, district, confID) values ('George Mason', 'Mustangs', 2, 'Y', 'Bull Run', 35);
insert into teams (school, mascot, class, tracked, district, confID) values ('Strasburg', 'Rams', 2, 'Y', 'Bull Run', 35);
insert into teams (school, mascot, class, tracked, district, confID) values ('Nelson Co.', 'Governors', 2, 'Y', 'Dogwood', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('Arcadia', 'Firebirds', 2, 'Y', 'Eastern Shore', 33);
insert into teams (school, mascot, class, tracked, district, confID) values ('Nandua', 'Warriors', 2, 'Y', 'Eastern Shore', 33);
insert into teams (school, mascot, class, tracked, district, confID) values ('Amelia Co.', 'Raiders', 2, 'Y', 'James River', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bluestone', 'Barons', 2, 'Y', 'James River', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Goochland', 'Bulldogs', 2, 'Y', 'James River', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Nottoway', 'Cougars', 2, 'Y', 'James River', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Prince Edward', 'Eagles', 2, 'Y', 'James River', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Washington & Lee', 'Eagles', 2, 'Y', 'Northern Neck', 33);
insert into teams (school, mascot, class, tracked, district, confID) values ('Buffalo Gap', 'Bison', 2, 'Y', 'Shenandoah', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('East Rockingham', 'Eagles', 2, 'Y', 'Shenandoah', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('Page Co.', 'Panthers', 2, 'Y', 'Shenandoah', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('Stuarts Draft', 'Cougars', 2, 'Y', 'Shenandoah', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('Wilson Memorial', 'Green Hornets', 2, 'Y', 'Shenandoah', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('King William', 'Cavaliers', 2, 'Y', 'Tidewater', 33);
insert into teams (school, mascot, class, tracked, district, confID) values ('Brunswick', 'Bulldogs', 2, 'Y', 'Tri-Rivers', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('Greensville', 'Eagles', 2, 'Y', 'Tri-Rivers', 34);
insert into teams (school, mascot, class, tracked, district, confID) values ('R.E. Lee (St)', 'Fighting Leemen', 2, 'Y', 'Valley', 36);
insert into teams (school, mascot, class, tracked, district, confID) values ('Grundy', 'Golden Wave', 2, 'Y', 'Black Diamond', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Appomattox', 'Raiders', 2, 'Y', 'Dogwood', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('Chatham', 'Cavaliers', 2, 'Y', 'Dogwood', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('Dan River', 'Wildcats', 2, 'Y', 'Dogwood', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('Gretna', 'Hawks', 2, 'Y', 'Dogwood', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('Marion', 'Scarlet Hurricanes', 2, 'Y', 'Hogoheegee', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Buckingham Co.', 'Knights', 2, 'Y', 'James River', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('Randolph-Henry', 'Statesmen', 2, 'Y', 'James River', 37);
insert into teams (school, mascot, class, tracked, district, confID) values ('John Battle', 'Trojans', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Central-Wise', 'Warriors', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Gate City', 'Blue Devils', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lee', 'Generals', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Ridgeview', 'xx', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Union', 'Bears', 2, 'Y', 'Mountain', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Graham', 'G-Men', 2, 'Y', 'Mountain Empire', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Grayson Co.', 'Blue Devils', 2, 'Y', 'Mountain Empire', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Martinsville', 'Bulldogs', 2, 'Y', 'Piedmont', 38);
insert into teams (school, mascot, class, tracked, district, confID) values ('James River (Bu)', 'Knights', 2, 'Y', 'Pioneer', 38);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lebanon', 'Pioneers', 2, 'Y', 'Southwest', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Richlands', 'Blue Tornado', 2, 'Y', 'Southwest', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Tazewell', 'Bulldogs', 2, 'Y', 'Southwest', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Virginia', 'Bearcats', 2, 'Y', 'Southwest', 39);
insert into teams (school, mascot, class, tracked, district, confID) values ('Gate City', 'xx', 2, 'Y', 'Three Rivers', 40);
insert into teams (school, mascot, class, tracked, district, confID) values ('Giles', 'Spartans', 2, 'Y', 'Three Rivers', 38);
insert into teams (school, mascot, class, tracked, district, confID) values ('Glenvar', 'Highlanders', 2, 'Y', 'Three Rivers', 38);
insert into teams (school, mascot, class, tracked, district, confID) values ('Floyd Co.', 'Buffaloes', 2, 'Y', 'Three Rivers', 38);
insert into teams (school, mascot, class, tracked, district, confID) values ('Altavista', 'Colonels', 1, 'Y', 'Dogwood', 44);
insert into teams (school, mascot, class, tracked, district, confID) values ('William Campbell', 'Generals', 1, 'Y', 'Dogwood', 44);
insert into teams (school, mascot, class, tracked, district, confID) values ('Northampton', 'Yellow Jackets', 1, 'Y', 'Eastern Shore', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Central (Lun)', 'Chargers', 1, 'Y', 'James River', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('Cumberland', 'Dukes', 1, 'Y', 'James River', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('Colonial Beach', 'Drifters', 1, 'Y', 'Northern Neck', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Essex', 'Trojans', 1, 'Y', 'Northern Neck', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Lancaster', 'Red Devils', 1, 'Y', 'Northern Neck', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Northumberland', 'Indians', 1, 'Y', 'Northern Neck', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rappahnannock', 'Raiders', 1, 'Y', 'Northern Neck', 43);
insert into teams (school, mascot, class, tracked, district, confID) values ('Stonewall Jackson (Qui)', 'Generals', 1, 'Y', 'Shenandoah', 44);
insert into teams (school, mascot, class, tracked, district, confID) values ('Luray', 'Bulldogs', 1, 'Y', 'Shenandoah', 44);
insert into teams (school, mascot, class, tracked, district, confID) values ('Riverheads', 'Gladiators', 1, 'Y', 'Shenandoah', 44);
insert into teams (school, mascot, class, tracked, district, confID) values ('Charles City', 'Panthers', 1, 'Y', 'Tidewater', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('King & Queen', 'Royal Tigers', 1, 'Y', 'Tidewater', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('Mathews', 'Blue Devils', 1, 'Y', 'Tidewater', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('Middlesex', 'Chargers', 1, 'Y', 'Tidewater', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('West Point', 'Pointers', 1, 'Y', 'Tidewater', 42);
insert into teams (school, mascot, class, tracked, district, confID) values ('Franklin', 'Broncos', 1, 'Y', 'Tri-Rivers', 41);
insert into teams (school, mascot, class, tracked, district, confID) values ('Surry', 'Cougars', 1, 'Y', 'Tri-Rivers', 41);
insert into teams (school, mascot, class, tracked, district, confID) values ('Sussex', 'Tigers', 1, 'Y', 'Tri-Rivers', 41);
insert into teams (school, mascot, class, tracked, district, confID) values ('Windsor', 'Dukes', 1, 'Y', 'Tri-Rivers', 41);
insert into teams (school, mascot, class, tracked, district, confID) values ('Honaker', 'Tigers', 1, 'Y', 'Black Diamond', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('Hurley', 'Rebels', 1, 'Y', 'Black Diamond', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('Twin Valley', 'Panthers', 1, 'Y', 'Black Diamond', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('J.I. Burton', 'Raiders', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Castlewood', 'Blue Devils', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Eastside', 'Spartans', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rye Cove', 'Eagles', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Twin Springs', 'Titans', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Thomas Walker', 'Pioneers', 1, 'Y', 'Cumberland', 48);
insert into teams (school, mascot, class, tracked, district, confID) values ('Chilhowie', 'Warriors', 1, 'Y', 'Hogoheegee', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('Patrick Henry (GS', 'Rebels', 1, 'Y', 'Hogoheegee', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('Holston', 'Cavaliers', 1, 'Y', 'Hogoheegee', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('Northwood', 'Panthers', 1, 'Y', 'Hogoheegee', 47);
insert into teams (school, mascot, class, tracked, district, confID) values ('Rural Retreat', 'Indians', 1, 'Y', 'Hogoheegee', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('George Wythe (Wy)', 'Maroons', 1, 'Y', 'Hogoheegee', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bland Co.', 'Bears', 1, 'Y', 'Mountain Empire', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('Fort Chiswell', 'Pioneers', 1, 'Y', 'Mountain Empire', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('Galax', 'Maroon Tide', 1, 'Y', 'Mountain Empire', 46);
insert into teams (school, mascot, class, tracked, district, confID) values ('Narrows', 'Green Wave', 1, 'Y', 'Mountain Empire', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Bath Co.', 'Chargers', 1, 'Y', 'Pioneer', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Covington', 'Cougars', 1, 'Y', 'Pioneer', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Craig Co.', 'Rockets', 1, 'Y', 'Pioneer', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Parry McCluer', 'Fighting Blues', 1, 'Y', 'Pioneer', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Auburn', 'Eagles', 1, 'Y', 'Three Rivers', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Eastern Montgomery', 'Mustangs', 1, 'Y', 'Three Rivers', 45);
insert into teams (school, mascot, class, tracked, district, confID) values ('Radford', 'Bobcats', 1, 'Y', 'Three Rivers', 45);


insert into teams (school, mascot, class, tracked) values ('Athens (NC)', 'xx', 6, 'N');
insert into teams (school, mascot, class, tracked) values ('Northwestern (SC)', 'xx', 6, 'N');
insert into teams (school, mascot, class, tracked) values ('Hillside (NC)', 'xx', 5, 'N');
insert into teams (school, mascot, class, tracked) values ('Okeechobee (Fl)', 'xx', 5, 'N');
insert into teams (school, mascot, class, tracked) values ('Vance (NC)', 'xx', 5, 'N');
insert into teams (school, mascot, class, tracked) values ('Woodrow Wilson (DC)', 'xx', 5, 'N');
insert into teams (school, mascot, class, tracked) values ('Alleghany (NC)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Avalon (MD)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Col. Richardson', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('East Hardy (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Greenbrier West (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Hancock Co. (TN)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Harlan Independent (KY)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Jenkins (KY)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Montcalm (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('North Stokes (NC)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Paintsville (KY)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Pendleton Co. (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Phelps (KY)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Pocahontas (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Snow Hill (MD)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('South Floyd (KY)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Unaka (TN)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Van (WV)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Weldon (NC)', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Broadwater Acad.', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Charlotte Christian', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Grace Christian', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Greenbriar Acad.', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Kenston Forest', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Portsmouth Christian', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Quantico', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Roanoke Catholic', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Trinity Episcopal', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Word of God', 'xx', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Bartlett Yancey (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Cambridge/S.Dorchester (MD)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Cocoa (Fl)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Currituck (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Eastern (DC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('First Flight (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Letcher Co. (KY)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('McMichael (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Morehead (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Northeastern (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Potomac (MD)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Roanoke Rapids (NC)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Spring Mills (WV)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Sullivan South (TN)', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Woodberry Forest', 'xx', 3, 'N');
insert into teams (school, mascot, class, tracked) values ('Bluefield (WV)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('East Ridge (KY)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Fort Hill (MD)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Holmes (NC)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Kent (MD)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('McCreary Central (KY)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('River View (WV)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Shelby Valley (KY)', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Benedictine', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Fork Union', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Saint John Paul', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('St. Christophers', 'xx', 2, 'N');
insert into teams (school, mascot, class, tracked) values ('Rappahannock Co.', 'Panthers', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('Chincoteague', 'Ponies', 1, 'N');
insert into teams (school, mascot, class, tracked) values ('J.M. Bennett (MD)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Bishop McNamara', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('David Crockett (TN)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Hedgesville (WV)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Jefferson Co. (WV)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Martinsburg (WV)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Person (NC)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Tennessee (TN)', 'xx', 4, 'N');
insert into teams (school, mascot, class, tracked) values ('Washington (WV)', 'xx', 4, 'N');